// client/src/templates/Hero.tsx
import NavButton from '../components/NavButton';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowRight } from '@fortawesome/free-solid-svg-icons';
import Loading from '../layouts/Loading';
import { useGetResourceById } from '../hooks/dataHooks';
import { Asset } from '../types/assetTypes';
import ErrorPage from '../layouts/Error';

export const Hero = () => {
	const { data: hero, isLoading, isError } = useGetResourceById<Asset>('assets', 'hero');

	if (isLoading) return <Loading />;
	if (isError) return <ErrorPage />;

	return hero ? (
		<div className="hero">
			<div className="overlay" />
			<video src={hero.media} autoPlay loop muted playsInline />
			<div className="hero-content">
				<h1 className="hero-head">The foundation for Health & Performance</h1>
				<p className="hero-para">Reach your wellness potential with our comprehnsive formulas</p>
				<ul className="nav-button">
					<NavButton to="/shop" icon={<FontAwesomeIcon icon={faArrowRight} />} label="Shop Primal Formulas" />
				</ul>
			</div>
		</div>
	) : null;
};

export default Hero;

// client/src/app/components/hero/hero.component.ts
import { Component, OnInit } from '@angular/core';
import { Asset } from '../../models/models';
import { AssetService } from '../../services/asset/asset.service';
import { catchError, finalize, of } from 'rxjs';
import { LoadingSpinnerComponent } from '../loading-spinner/loading-spinner.component';
import { NavButtonComponent } from '../nav-button/nav-button.component';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [LoadingSpinnerComponent, NavButtonComponent],
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.css',
})
export class HeroComponent {
  data: Asset | null = null;
  loading: boolean = false;
  error: string | null = null;

  constructor(private assetService: AssetService) {}

  ngOnInit(): void {
    this.loadAsset();
  }

  private loadAsset(): void {
    this.loading = true;
    this.error = null;

    this.assetService
      .fetchAsset('Hero')
      .pipe(
        catchError((err: Error) => {
          this.error = 'Error loading asset';
          return of(null);
        }),
        finalize(() => (this.loading = false))
      )
      .subscribe((data) => (this.data = data));
  }
}

<section id="hero-section">

    <div class="overlay">
        <h1 class="overlay-heading">The Foundation for health & performance</h1>
        <p class="overlay-subheading">Reach your wellness potential with our comprehensive formulas
        </p>
        <app-nav-button link="/products" text="Shop Primal Formulas" iconName="arrow-right" />
    </div>

    <div class="hero">
        @if (loading) {
        <app-loading-spinner />
        } @else if (data?.content) {
        <video [src]="data?.content" autoplay loop playsInline preload="auto"></video>
        }

    </div>

</section>
