// client/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import {
  faFacebook,
  faInstagram,
  faTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';
import { NavButtonComponent } from '../nav-button/nav-button.component';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { ToTopButtonComponent } from '../to-top-button/to-top-button.component';
import { NavLogoComponent } from '../nav-logo/nav-logo.component';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    NavButtonComponent,
    FontAwesomeModule,
    ToTopButtonComponent,
    NavLogoComponent,
  ],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css',
})
export class FooterComponent {
  twitter = faTwitter;
  facebook = faFacebook;
  youtube = faYoutube;
  instagram = faInstagram;
}

<footer class="footer">
    <div class="footer-info">
        <h1 class="section-heading">Primal Formulas Ltd.</h1>
        <ul class="address-list">
            <li class="address-item">Clonross, Drumree</li>
            <li class="address-item">Co. Meath,</li>
            <li class="address-item">A85 PK30</li>
            <li class="address-item">Tel: 01 - 8259289</li>
            <li class="address-item">
                Email: info&#64;primalformulas.ie
            </li>
        </ul>
    </div>
    <div class="footer-links">
        <app-nav-logo class="footer-logo" [logoWidth]="150" [logoHeight]="150" />
        <div class="social-links">
            <fa-icon [icon]="facebook" class="icon" size="2x" />
            <fa-icon [icon]="twitter" class="icon" size="2x" />
            <fa-icon [icon]="youtube" class="icon" size="2x" />
            <fa-icon [icon]="instagram" class="icon" size="2x" />
        </div>
    </div>
    <div class="footer-nav">
        <app-nav-button link="/about" text="About Us" iconName="bracket-right" />
        <app-nav-button link="/products" text="Products" iconName="bracket-right" />
        <app-nav-button link="/cart" text="Cart" iconName="bracket-right" />
        <app-nav-button link="/account" text="Account" iconName="bracket-right" />
    </div>
    <app-to-top-button />
</footer>

// client/src/layouts/Footer.tsx
import { Link } from 'react-router-dom';
import { Asset } from '../types/assetTypes';
import { useGetResourceById } from '../hooks/dataHooks';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFacebook, faTwitter, faInstagram, faYoutube } from '@fortawesome/free-brands-svg-icons';

import Loading from './Loading';
import NavItem from '../components/NavItem';
import ToTopButton from '../components/ToTopButton';

function Footer() {
	const { data: logo, isLoading, isError, error } = useGetResourceById<Asset>('assets', 'logo');

	if (isLoading) return <Loading />;
	if (isError) return <div>Error: {error.message}</div>;

	return (
		<footer>
			<div className="footer-navigation">
				<ul className="nav-list">
					<NavItem to="/about">About</NavItem>
					<NavItem to="/shop">Products</NavItem>
					<NavItem to="/cart">Cart</NavItem>
					<NavItem to="/login">Login</NavItem>
				</ul>
			</div>
			<div className="footer-information">
				<Link to="/">
					<img src={logo?.media} alt="Logo" id="logo" />
				</Link>
				<ul className="address-list">
					<li className="address-item">Primal Formulas Ltd.</li>
					<li className="address-item">Clonross, Drumree</li>
					<li className="address-item">Co. Meath,</li>
					<li className="address-item">A85 PK30</li>
					<li className="address-item">Tel: 01 - 8259289</li>
					<li className="address-item">Email: info@primalformulas.ie</li>
				</ul>
			</div>
			<div className="social-links">
				<Link to="#" target="_blank" className="facebook socials">
					<FontAwesomeIcon icon={faFacebook} size="2xl" />
				</Link>
				<Link to="#" target="_blank" className="twitter socials">
					<FontAwesomeIcon icon={faTwitter} size="2xl" />
				</Link>
				<Link to="#" target="_blank" className="instagram socials">
					<FontAwesomeIcon icon={faInstagram} size="2xl" />
				</Link>
				<Link to="#" target="_blank" className="youtube socials">
					<FontAwesomeIcon icon={faYoutube} size="2xl" />
				</Link>
			</div>
			<ToTopButton />
		</footer>
	);
}

export default Footer;
