// client/src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { NavLogoComponent } from '../nav-logo/nav-logo.component';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { RouterModule } from '@angular/router';
import {
  faBars,
  faCartShopping,
  faUserCircle,
  faX,
} from '@fortawesome/free-solid-svg-icons';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [NavLogoComponent, FontAwesomeModule, RouterModule, CommonModule],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css',
})
export class SidebarComponent {
  faBars = faBars;
  faX = faX;
  faShopping = faCartShopping;
  faUserCircle = faUserCircle;

  private open = new BehaviorSubject<boolean>(false);

  public open$ = this.open.asObservable();

  public toggleSidebar() {
    this.open.next(!this.open.value);
  }
}

<div [ngClass]="{'open': (open$ | async)}" class="sidebar">

    <div class="sidebar-icon-open">
        <fa-icon [icon]="faX" class="navigation" size="2x" (click)="toggleSidebar()" />
        <app-nav-logo />
    </div>

    <nav class="sidebar-menu">
        <h1 class="section-heading"> <a [routerLink]="['/']">Primal Formulas</a></h1>

        <ul class="sidebar-list">
            <li class="sidebar-list-item"><a [routerLink]="['/about']" (click)="toggleSidebar()">Our
                    Story</a>
            </li>
            <li class="sidebar-list-item"><a [routerLink]="['/products']"
                    (click)="toggleSidebar()">Products</a>
            </li>
            <li class="sidebar-list-item"><a [routerLink]="['/account']"
                    (click)="toggleSidebar()">Account</a>
            </li>
        </ul>
        <div class="sidebar-nav">
            <div class="icon-link">
                <a routerLink="/account">
                    <fa-icon [icon]="faUserCircle" class="icon" size="2x"
                        (click)="toggleSidebar()" />
                </a>
            </div>

            <div class="icon-link">
                <a routerLink="/cart">
                    <fa-icon [icon]="faShopping" class="icon" size="2x" (click)="toggleSidebar()" />
                </a>
            </div>
        </div>
    </nav>

</div>

<div class="sidebar-icon">
    <fa-icon [icon]="faBars" class="navigation" size="2x" (click)="toggleSidebar()" />
    <app-nav-logo />
</div>

// frontend/src/layouts/Sidebar.tsx
import styles from '../styles/Sidebar.module.css';

import { Fragment } from 'react/jsx-runtime';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useSideNavbar } from '../hooks/navigationHooks';
import { faBars, faX, faCartShopping, faCircleUser } from '@fortawesome/free-solid-svg-icons';

import NavItem from '../components/NavItem';
import LogoHeading from '../components/LogoHeading';

function Sidebar() {
	const { isOpen, toggleSideNavbar } = useSideNavbar();

	return (
		<Fragment>
			<div className={isOpen ? styles.sidebar : styles.sidebarOpen}>
				<nav className={styles.sidebarMenu}>
					<LogoHeading headingText="Primal Formulas" />
					<ul className={styles.navList}>
						<NavItem to="/about">Our Story</NavItem>
						<NavItem to="/shop">Products</NavItem>
						<NavItem to="/login">Account</NavItem>
					</ul>
					<ul className={styles.iconNav}>
						<NavItem to="/cart">
							<FontAwesomeIcon icon={faCartShopping} size="lg" />
						</NavItem>
						<NavItem to="/login">
							<FontAwesomeIcon icon={faCircleUser} size="xl" />
						</NavItem>
					</ul>
				</nav>
				{isOpen && (
					<div className={styles.sidebarIcon} onClick={toggleSideNavbar}>
						<FontAwesomeIcon icon={faX} className={styles.navigation} />
					</div>
				)}
			</div>
			{!isOpen && (
				<div className={styles.sidebarIcon} onClick={toggleSideNavbar}>
					<FontAwesomeIcon icon={faBars} className={styles.navigation} />
				</div>
			)}
		</Fragment>
	);
}

export default Sidebar;
