// client/src/app/components/to-top-button/to-top-button.component.ts
import { Component } from '@angular/core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faChevronCircleUp } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-to-top-button',
  standalone: true,
  imports: [FontAwesomeModule],
  templateUrl: './to-top-button.component.html',
  styleUrl: './to-top-button.component.css',
})
export class ToTopButtonComponent {
  faChevron = faChevronCircleUp;

  scrollToTop() {
    window.scrollTo({
      top: 0,
      behavior: 'smooth',
    });
  }
}

<button class="to-top-button" (click)="scrollToTop()">
    <fa-icon [icon]="faChevron" class="to-top-icon" size=2x />
</button>

// client/src/components/ToTopButton.tsx
import { faArrowUp } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

const ToTopButton: React.FC = () => {
	const scrollToTop = () => {
		window.scrollTo({
			top: 0,
			behavior: 'smooth',
		});
	};
	return (
		<button id="toTopButton" aria-label="scroll-to-top-button" className="toTopButton" onClick={scrollToTop}>
			<FontAwesomeIcon icon={faArrowUp} size="2x" />
		</button>
	);
};

export default ToTopButton;
